site_name: mkdocs_aps105-book
nav:
  - Home: cover.md
  - Preface:
      - Introduction: chapters/preface/intro.md
      - Principles: chapters/preface/principles.md
  - "Book Chapters":
      - Introduction to Computers:
          - Introduction: chapters/chapter01-computers/intro.md
          - Basic Structure: chapters/chapter01-computers/basic-structure.md
          - Main Memory: chapters/chapter01-computers/main-memory.md
          - Development Cycle: chapters/chapter01-computers/dev-cycle.md
          - Simple C Code: chapters/chapter01-computers/simple-C-code.md
      - Variables and Data:
          - Introduction: chapters/chapter02-variables/intro.md
          - Data Types: chapters/chapter02-variables/data-types.md
          - Storing Data: chapters/chapter02-variables/storing-data.md
          - Operations: chapters/chapter02-variables/operations.md
          - Math Library: chapters/chapter02-variables/math-library.md
          - Random Number Generation: chapters/chapter02-variables/random-number.md
          - Exercises: chapters/chapter02-variables/exercises.md
      - Decision Making:
          - Introduction: chapters/chapter03-decision-making/intro.md
          - If Statement: chapters/chapter03-decision-making/if-statement.md
          - Multiple Conditions: chapters/chapter03-decision-making/multiple-conditions.md
          - Nested If Statements: chapters/chapter03-decision-making/nested-if.md
          - Exercises: chapters/chapter03-decision-making/exercises.md
      - Loops:
          - Introduction: chapters/chapter04-loops/intro.md
          - While Loop: chapters/chapter04-loops/while.md
          - Do-While Loop: chapters/chapter04-loops/do-while.md
          - For Loop: chapters/chapter04-loops/for-loop.md
          - Nested Loops: chapters/chapter04-loops/nested-loops.md
          - Debugging Loops: chapters/chapter04-loops/debugging-loops.md
          - Exercises: chapters/chapter04-loops/exercises.md
      - Functions:
          - Introduction: chapters/chapter05-functions/intro.md
          - Functions: chapters/chapter05-functions/functions.md
          - Communication from Functions: chapters/chapter05-functions/communicate-from-function.md
          - Variable Scope: chapters/chapter05-functions/variable-scope.md
          - Passing Multiple Values: chapters/chapter05-functions/pass-more-values.md
          - Exercises: chapters/chapter05-functions/exercises.md
      - Pointers:
          - Introduction: chapters/chapter06-pointers/intro.md
          - Why Pointers?: chapters/chapter06-pointers/why-pointers.md
          - What are Pointers?: chapters/chapter06-pointers/what-are-pointers.md
          - How to Use Pointers: chapters/chapter06-pointers/how-to-use-pointers.md
          - Scope: chapters/chapter06-pointers/scope.md
          - Goldbach Conjecture Example: chapters/chapter06-pointers/goldbach-conjecture-example.md
          - Exercises: chapters/chapter06-pointers/exercises.md
      - Arrays:
          - Introduction: chapters/chapter07-arrays/intro.md
          - Why Arrays?: chapters/chapter07-arrays/why-arrays.md
          - What are Arrays?: chapters/chapter07-arrays/what-are-arrays.md
          - Arrays in Functions: chapters/chapter07-arrays/arrays-functions.md
          - Exercises: chapters/chapter07-arrays/exercises.md
      - Dynamic Memory Allocation:
          - Introduction: chapters/chapter08-dynamic-memory-allocation/intro.md
          - Why and How of Dynamic Allocation: chapters/chapter08-dynamic-memory-allocation/why-how-dynamic-alloc.md
          - Exercises: chapters/chapter08-dynamic-memory-allocation/exercises.md
      - Multi-dimensional Arrays:
          - Introduction: chapters/chapter09-multi-dimensional-arrays/intro.md
          - Why 2D Arrays?: chapters/chapter09-multi-dimensional-arrays/why-2d.md
          - Passing 2D Arrays to Functions: chapters/chapter09-multi-dimensional-arrays/pass-2d-functions.md
          - 2D Dynamic Memory Allocation: chapters/chapter09-multi-dimensional-arrays/2d-dynamic-memory-alloc.md
          - Exercises: chapters/chapter09-multi-dimensional-arrays/exercises.md
      - Strings:
          - Introduction: chapters/chapter10-strings/intro.md
          - What are Strings?: chapters/chapter10-strings/what-are-strings.md
          - Input and Output with Strings: chapters/chapter10-strings/input-output-strings.md
          - String Functions: chapters/chapter10-strings/string-functions.md
          - Array of Strings: chapters/chapter10-strings/array-of-strings.md
          - Exercises: chapters/chapter10-strings/exercises.md
      - Recursion:
          - Introduction: chapters/chapter11-recursion/intro.md
          - Recursion in Mathematics: chapters/chapter11-recursion/recursion-math.md
          - Recursion in Patterns: chapters/chapter11-recursion/recursion-in-patterns.md
          - Recursion in Arrays: chapters/chapter11-recursion/recursion-in-arrays.md
          - Exercises: chapters/chapter11-recursion/exercises.md
      - Data Structures:
          - Introduction: chapters/chapter12-data-structures/intro.md
          - What is a Data Structure?: chapters/chapter12-data-structures/what-data-structure.md
          - Pointers to Data Structures: chapters/chapter12-data-structures/pointers-to-data-structure.md
          - Exercises: chapters/chapter12-data-structures/exercises.md
      - Linked Lists:
          - Introduction: chapters/chapter13-linked-lists/intro.md
          - Why Linked Lists?: chapters/chapter13-linked-lists/why-linked-lists.md
          - Forming a Linked List: chapters/chapter13-linked-lists/form-linked-list.md
          - Inserting, Finding, and Observing in Linked Lists: chapters/chapter13-linked-lists/insert-find-observe-into-linkedlist.md
          - Deleting Nodes: chapters/chapter13-linked-lists/delete-nodes.md
          - Exercises: chapters/chapter13-linked-lists/exercises.md
      - Sorting Algorithms:
          - Introduction: chapters/chapter14-sorting/intro.md
          - Insertion Sort: chapters/chapter14-sorting/insertion-sort.md
          - Selection Sort: chapters/chapter14-sorting/selection-sort.md
          - Bubble Sort: chapters/chapter14-sorting/bubble-sort.md
          - Exercises: chapters/chapter14-sorting/exercises.md
      - Searching Algorithms:
          - Introduction: chapters/chapter15-searching/intro.md
          - Sequential Search: chapters/chapter15-searching/sequential-search.md
          - Binary Search: chapters/chapter15-searching/binary-search.md
          - Exercises: chapters/chapter15-searching/exercises.md
  - "Appendix: Additional Information":
      - Appendix: chapters/appendix/appendix.md
      - Setup VS Code: chapters/appendix/setup-vscode.md
      - VS Code Extensions: chapters/appendix/vscode-extensions.md
      - Coding Style: chapters/appendix/coding-style.md
      - Debugging: chapters/appendix/debugging.md
      - Unix Commands: chapters/appendix/unix-commands.md

theme:
  name: material
